### ISSUE TITLE
 'CRAN_package_db' is not an exported object from 'namespace:tools'

### ISSUE THREAD

**Issue by SteffenMoritz** [jsugarelli/packagefinder#3]
Just tried to run the example as it is...did not work.

> index <- buildIndex(filename = file.path(tempdir(), "searchindex.rdata"), download.stats = FALSE)
Fehler: 'CRAN_package_db' is not an exported object from 'namespace:tools'
>

**Comment by jsugarelli** [comment]
Actually, `tools` DOES export `CRAN_package_db()`. Can you please help me by finding out the version of `tools` that you are using? Just run `packageVersion("tools")` on the R console. Thanks!

**Comment by SteffenMoritz** [comment]
> packageVersion("tools")
[1] ‘3.3.2’

**Comment by SteffenMoritz** [comment]
Guess 3.5.1 is the current version. I will try tomorrow if it works if I update.
UPDATE:
This is more difficult than I thought. tools somehow does not behave like a normal package.
> old.packages() does not mention that the package is old
update.packages did not update the package

https://cran.r-project.org/package=tools leads nowhere

Guess tools rather is kind of system package than a normal package.

Maybe I have to update the R version itself...?

**Comment by jsugarelli** [comment]
Yes, that must be the problem. According to [https://www.rdocumentation.org/](https://www.rdocumentation.org/) `CRAN_package_db()` is only available from `tools` version 3.4.0 onwards.

`tools` is an R built-in package. `install.packages("tools", dependencies=TRUE)`  doesn't work either. It seems indeed that you need to update R to the latest version (which makes sense anyway).

With the next version of `packagefinder` I will specify the dependencies accordingly, so that `tools  >= 3.4.0` is required to run `packagefinder`.

**Comment by SteffenMoritz** [comment]
Maybe it would be a good idea to directly depend on a certain R version instead of a tools version. Otherwise users might run into the same questions / problems I were running into. (why can't I update tools package)

Something like:
Depends:
    R (>= 3.?.?)

With ? being the first R version that has the appropriate tools version.

**Comment by jsugarelli** [comment]
Absolutely correct, I'll do it this way.

**Comment by jsugarelli** [comment]
Depends clause added to DESCRIPTION file in new release 0.1.0.
